WebApp/Pages/GameConfiguration/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DAL;
using Domain;

namespace WebApp.Pages_GameConfiguration
{
    public class CreateModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public CreateModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty] public GameConfig GameConfig { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.GameConfigs.Add(GameConfig);
            await _context.SaveChangesAsync();

            return RedirectToPage("../GameConfiguration/Edit", new {id = GameConfig.GameConfigId});
        }
        [HttpPost]
        public IActionResult Index(ShipTouchRuleViewModel model)
        {
            return Content(model.EShipTouchRule.ToString());
        }
    }
    public class ShipTouchRuleViewModel
    {
        public BattleShipBrain.EShipTouchRule EShipTouchRule { get; set; }
    }
}

WebApp/Pages/GameConfiguration/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages_GameConfiguration
{
    public class DeleteModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public DeleteModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GameConfig GameConfig { get; set; }  = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameConfig = await _context.GameConfigs.FirstOrDefaultAsync(m => m.GameConfigId == id);

            if (GameConfig == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameConfig = await _context.GameConfigs.FindAsync(id);

            if (GameConfig != null)
            {
                var gameShipConfigs = _context.GameShipConfig.Where(gsc => gsc.GameConfigId == GameConfig.GameConfigId);

                foreach (var gameShipConfig in gameShipConfigs)
                {
                    _context.GameShipConfig.Remove(gameShipConfig);
                }

                await _context.SaveChangesAsync();
                
                _context.GameConfigs.Remove(GameConfig);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/GameConfiguration/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages_GameConfiguration
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public DetailsModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        public GameConfig GameConfig { get; set; }  = default!;
        public List<GameShipConfig> GameShipConfigs { get; set; }  = default!;
        

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameConfig = await _context.GameConfigs.FirstOrDefaultAsync(m => m.GameConfigId == id);
            GameShipConfigs = _context.GameShipConfig.Where(m => m.GameConfigId == id).ToList();
            

            if (GameConfig == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WebApp/Pages/GameConfiguration/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BattleShipBrain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages_GameConfiguration
{
    public class EditModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public EditModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GameConfig GameConfig { get; set; }  = default!;
        public List<GameShipConfig> GameShipConfigs { get; set; }  = default!;
        
        public bool IsError { get; set; } = false;

        public async Task<IActionResult> OnGetAsync(int? id, string? message)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            if (message == "error")
            {
                IsError = true;
            }

            GameConfig = await _context.GameConfigs.FirstOrDefaultAsync(m => m.GameConfigId == id);
            GameShipConfigs = _context.GameShipConfig.Where(m => m.GameConfigId == id).ToList();
            
            if (GameConfig == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (GameConfig.BoardSizeX < 3 && GameConfig.BoardSizeY < 3)
            {
                GameConfig.Complete = 0;
                _context.Update(GameConfig);
                await _context.SaveChangesAsync();
                return RedirectToPage("/", new {id = GameConfig.GameConfigId, message = "error"});
            }

            var gameConfiguration = new GameConfiguration
            {
                BoardSizeX = GameConfig.BoardSizeX,
                BoardSizeY = GameConfig.BoardSizeY,
                EShipTouchRule = (EShipTouchRule) GameConfig.EShipTouchRule,
                ShipConfigs = new List<ShipConfig>()
            };

            var shipConfigsFromDb = _context.GameShipConfig.Where(gsc => gsc.GameConfigId == GameConfig.GameConfigId);
            foreach (var gameShipConfig in shipConfigsFromDb)
            {
                gameConfiguration.ShipConfigs.Add(new ShipConfig
                {
                    Name = gameShipConfig.ShipName,
                    Quantity = gameShipConfig.Quantity,
                    ShipSizeY = gameShipConfig.ShipSizeY,
                    ShipSizeX = gameShipConfig.ShipSizeX
                });
            }

            if (!gameConfiguration.ControlIfConfigurationIsPossible())
            {
                GameConfig.Complete = 0;
                _context.Update(GameConfig);
                await _context.SaveChangesAsync();
                return RedirectToPage("", new {id = GameConfig.GameConfigId, message = "error"});
            }

            GameConfig.Complete = 1;
            _context.Attach(GameConfig).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GameConfigExists(GameConfig.GameConfigId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }
        
        [HttpPost]
        public IActionResult Index(ShipTouchRuleViewModel model)
        {
            return Content(model.EShipTouchRule.ToString());
        }

        private bool GameConfigExists(int id)
        {
            return _context.GameConfigs.Any(e => e.GameConfigId == id);
        }
    }
}

WebApp/Pages/GameConfiguration/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BattleShipBrain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;
using WebApp.Pages_ShipConfiguration;

namespace WebApp.Pages_GameConfiguration
{
    public class IndexModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public IndexModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<GameConfig> GameConfig { get;set; }  = default!;
        public List<string> LocalGameConfig { get;set; }  = default!;
        
        public async Task OnGetAsync()
        {
            var lsa = new LocalStorageAccess(GlobalPath.BattleShipPath);
            LocalGameConfig = new List<string>(lsa.GetConfigurationFileNames());
            GameConfig = await _context.GameConfigs.ToListAsync();
        }

        public async Task<bool> IsInUse(int id)
        {
            return _context.GameSaves.Any(gs => gs.GameConfigId == id);
        }

        [BindProperty]
        public string ConfigName { get; set; } = default!;
        
        public async Task<IActionResult> OnPostSaveToDb()
        {
            var lsa = new LocalStorageAccess(GlobalPath.BattleShipPath);
            var config = lsa.GetConfiguration(ConfigName);
            var game = _context.GameConfigs.Add(new GameConfig
            {
                ConfigName = ConfigName,
                BoardSizeX = config!.BoardSizeX,
                BoardSizeY = config!.BoardSizeY,
                EShipTouchRule = (int) config.EShipTouchRule,
            });

            await _context.SaveChangesAsync();
            
            foreach (var shipConfig in config.ShipConfigs)
            {
                _context.GameShipConfig.Add(new GameShipConfig
                {
                    ShipName = shipConfig.Name,
                    Quantity = shipConfig.Quantity,
                    ShipSizeX = shipConfig.ShipSizeX,
                    ShipSizeY = shipConfig.ShipSizeY,
                    GameConfigId = game.Entity.GameConfigId,
                });
            }
            
            await _context.SaveChangesAsync();

            return RedirectToPage("");
        }
        [BindProperty]
        public int GameConfigId { get; set; } = default!;
        public async Task<IActionResult> OnPostUploadToLocal()
        {
            var configurationFromDb = await _context.GameConfigs.FindAsync(GameConfigId);
            var lsa = new LocalStorageAccess(GlobalPath.BattleShipPath);

            var shipConfigs = new List<ShipConfig>();
            foreach (var gameShipConfig in  _context.GameShipConfig.Where(gsc => gsc.GameConfigId == configurationFromDb.GameConfigId))
            {
                shipConfigs.Add(new ShipConfig
                {
                    Name = gameShipConfig.ShipName,
                    Quantity = gameShipConfig.Quantity,
                    ShipSizeX = gameShipConfig.ShipSizeX,
                    ShipSizeY = gameShipConfig.ShipSizeY
                });
            }

            var gameConfiguration = new GameConfiguration
            {
                BoardSizeX = configurationFromDb.BoardSizeX,
                BoardSizeY = configurationFromDb.BoardSizeY,
                EShipTouchRule = (EShipTouchRule) configurationFromDb.EShipTouchRule,
                Name = configurationFromDb.ConfigName,
                ShipConfigs = shipConfigs
            };
            
            lsa.SaveConfiguration(configurationFromDb.ConfigName, gameConfiguration);
            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/GameSave/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DAL;
using Domain;

namespace WebApp.Pages_GameSave
{
    public class CreateModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public CreateModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["GameConfigId"] = new SelectList(_context.GameConfigs, "GameConfigId", "ConfigName");
            return Page();
        }

        [BindProperty]
        public GameSave GameSave { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.GameSaves.Add(GameSave);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/GameSave/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages_GameSave
{
    public class DeleteModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public DeleteModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GameSave GameSave { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameSave = await _context.GameSaves
                .Include(g => g.GameConfig).FirstOrDefaultAsync(m => m.GameSaveId == id);

            if (GameSave == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameSave = await _context.GameSaves.FindAsync(id);

            if (GameSave != null)
            {
                _context.GameSaves.Remove(GameSave);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

WebApp/Pages/GameSave/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DAL;
using Domain;

namespace WebApp.Pages_GameSave
{
    public class DetailsModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public DetailsModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        public GameSave GameSave { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GameSave = await _context.GameSaves
                .Include(g => g.GameConfig).FirstOrDefaultAsync(m => m.GameSaveId == id);

            if (GameSave == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

WebApp/Pages/ShipConfiguration/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DAL;
using Domain;

namespace WebApp.Pages_ShipConfiguration
{
    public class CreateModel : PageModel
    {
        private readonly DAL.ApplicationDbContext _context;

        public CreateModel(DAL.ApplicationDbContext context)
        {
            _context = context;
        }

        public int GameConfigId { get; set; }

        public IActionResult OnGet(int? id)
        {
    
            if (id == null)
            {
                return NotFound();
            }

            GameConfigId = (int) id;
            ViewData["GameConfigId"] = new SelectList(_context.GameConfigs, "GameConfigId", "ConfigName");
                return Page();
        }

        [BindProperty]
        public GameShipConfig GameShipConfig { get; set; }  = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.GameShipConfig.Add(GameShipConfig);
            await _context.SaveChangesAsync();

            return RedirectToPage("../GameConfiguration/Edit", new {id = GameShipConfig.GameConfigId});
        }
    }
}

WebApp/Pages/GameConfiguration/Create.cshtml
@page
@using WebApp.Pages_GameConfiguration
@using BattleShipBrain
@model WebApp.Pages_GameConfiguration.CreateModel

@{
    ViewData["Title"] = "Create configuration";
}

<h2>Create configuration</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GameConfig.ConfigName" class="control-label"></label>
                <input asp-for="GameConfig.ConfigName" class="form-control" />
                <span asp-validation-for="GameConfig.ConfigName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameConfig.BoardSizeX" class="control-label"></label>
                <input asp-for="GameConfig.BoardSizeX" class="form-control" />
                <span asp-validation-for="GameConfig.BoardSizeX" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameConfig.BoardSizeY" class="control-label"></label>
                <input asp-for="GameConfig.BoardSizeY" class="form-control" />
                <span asp-validation-for="GameConfig.BoardSizeY" class="text-danger"></span>
            </div>
              <input type="hidden" asp-for="GameConfig.Complete" value="0" class="form-control" />
            <div class="form-group">
                <label asp-for="GameConfig.EShipTouchRule" class="control-label"></label>
                <select asp-for="GameConfig.EShipTouchRule" asp-items="Html.GetEnumSelectList<EShipTouchRule>()" class="form-control"></select>
                <span asp-validation-for="GameConfig.EShipTouchRule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add ships" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Pages/GameConfiguration/Delete.cshtml
@page
@model WebApp.Pages_GameConfiguration.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GameConfig</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GameConfig.ConfigName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GameConfig.ConfigName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GameConfig.BoardSizeX)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GameConfig.BoardSizeX)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GameConfig.BoardSizeY)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GameConfig.BoardSizeY)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GameConfig.EShipTouchRule)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GameConfig.EShipTouchRule)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="GameConfig.GameConfigId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

WebApp/Pages/GameConfiguration/Details.cshtml
@page
@model WebApp.Pages_GameConfiguration.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Game configuration details</h2>

    <hr />
    
    <div class="row">
        <div class="col">
            <h3>Board:</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">@Html.DisplayNameFor(model => model.GameConfig.ConfigName): @Model.GameConfig.ConfigName</li>
                <li class="list-group-item">@Html.DisplayNameFor(model => model.GameConfig.BoardSizeX): @Model.GameConfig.BoardSizeX</li>
                <li class="list-group-item">@Html.DisplayNameFor(model => model.GameConfig.BoardSizeY): @Model.GameConfig.BoardSizeY</li>
                <li class="list-group-item"> @Html.DisplayNameFor(model => model.GameConfig.EShipTouchRule): @GetRuleName(Model.GameConfig.EShipTouchRule)</li>
            </ul>
        </div>
        <div class="col">
            <h3>Ships:</h3>
            <ul class="list-group list-group-flush">
                @foreach (var ship in Model.GameShipConfigs)
                {
                    <li class="list-group-item">@ship.ShipName | @ship.Quantity | @ship.ShipSizeX x @ship.ShipSizeY</li>
                }
            </ul>
        </div>
    </div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@functions
{
    public string GetRuleName(int i)
    {
        switch (i)
        {
            case 1:
                return "No touch rule";
            case 2:
                return "Corner touch rule";
            case 3:
                return "Side touch rule";
        }
        return "";
    }
}

WebApp/Pages/GameConfiguration/Edit.cshtml
@page
@using BattleShipBrain
@model WebApp.Pages_GameConfiguration.EditModel

@{
    ViewData["Title"] = "Edit configuration";
}

<h2>Game configuration:</h2>

@if (Model.IsError)
{
    <div class="alert alert-danger" role="alert">
        Inpossible configuration! Board size must be grater than 3. Board must be able to fit all ships.
    </div>
}

<div class="row">
    <div class="col">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GameConfig.GameConfigId" />
            <div class="form-group">
                <label asp-for="GameConfig.ConfigName" class="control-label"></label>
                <input asp-for="GameConfig.ConfigName" class="form-control" />
                <span asp-validation-for="GameConfig.ConfigName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameConfig.BoardSizeX" class="control-label"></label>
                <input asp-for="GameConfig.BoardSizeX" class="form-control" />
                <span asp-validation-for="GameConfig.BoardSizeX" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameConfig.BoardSizeY" class="control-label"></label>
                <input asp-for="GameConfig.BoardSizeY" class="form-control" />
                <span asp-validation-for="GameConfig.BoardSizeY" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameConfig.EShipTouchRule" class="control-label"></label>
                <select asp-for="GameConfig.EShipTouchRule" asp-items="Html.GetEnumSelectList<EShipTouchRule>()" class="form-control"></select>
                <span asp-validation-for="GameConfig.EShipTouchRule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th>Ships</th>
                    <th><a class="badge badge-primary" asp-page="../ShipConfiguration/Create" asp-route-id="@Model.GameConfig.GameConfigId"> Add new ship </a></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.GameShipConfigs)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShipName) |
                        @Html.DisplayFor(modelItem => item.ShipSizeX) x @Html.DisplayFor(modelItem => item.ShipSizeY) |
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        <a asp-page="../ShipConfiguration/Edit" asp-route-id="@item.GameShipConfigId">Edit</a> |
                        <a asp-page="../ShipConfiguration/Delete" asp-route-id="@item.GameShipConfigId">Delete</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Pages/GameConfiguration/Index.cshtml
@page
@using BattleShipBrain
@using System.ComponentModel.DataAnnotations
@using System.Reflection
@model WebApp.Pages_GameConfiguration.IndexModel

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col">
        <div class="d-flex justify-content-between align-items-center">
            <div class="mr-auto p-2"><h3>Your game configurations</h3></div>
            <div class="p-2">
                <a class="btn btn-primary" asp-page="Create">Create New</a>
            </div>
        </div>
    </div>
</div>


<div class="row justify-content-center">
    <div class="col">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GameConfig[0].ConfigName)
                </th>
                <th>
                    Board size
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GameConfig[0].EShipTouchRule)
                </th>
                <th>
                    Action
                </th>
                <th>
                    Save
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.GameConfig)
            {
                var isInUse = Model.IsInUse(item.GameConfigId).Result;
                
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ConfigName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BoardSizeX) x  @Html.DisplayFor(modelItem => item.BoardSizeY)
                    </td>
                    <td>
                        @getRuleName(item.EShipTouchRule)
                    </td>
                    <td>
                        @if (isInUse)
                        {
                            <span class="badge badge-secondary" >Edit</span>
                            <span class="badge badge-secondary">Delete</span>}
                        else
                        {
                            <a class="badge badge-primary" asp-page="./Edit" asp-route-id="@item.GameConfigId">Edit</a> 
                            <a class="badge badge-primary" asp-page="./Delete" asp-route-id="@item.GameConfigId">Delete</a>  
                        }
                        <a class="badge badge-primary" asp-page="./Details" asp-route-id="@item.GameConfigId">Details</a>
                    </td>
                    <td>
                        <form method="post">
                            <input type="hidden" asp-for="GameConfigId" value="@item.GameConfigId">
                            <button type="submit" class="badge badge-primary" asp-page-handler="UploadToLocal" style="border: 0">Save to local storage</button>
                        </form>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

<h3>Local configuraitons</h3>
<div class="row">
    <div class="col-auto">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Name</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.LocalGameConfig)
                {
                    <tr>
                        <td>
                            @item
                        </td>
                        <td>
                            <form method="post">
                                <input asp-for="@Model.ConfigName" type="hidden" value="@item">
                                <input asp-page-handler="SaveToDb" type="submit" value="Upload" class="btn btn-primary btn-sm"/>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@functions
{
    public string getRuleName(int i)
    {
        switch (i)
        {
            case 1:
                return "No touch rule";
            case 2:
                return "Corner touch rule";
            case 3:
                return "Side touch rule";
        }
        return "";
    }
}